02 model spec
kenchasonakai/sample_app_for_rspec pull request #2
Opened 2020-10-08 15:02 UTC by kenchasonakai

taskモデルのバリデーションテストを作成しました。

2020-10-09 02:29 UTC, yuji91 requested changes
vimで作成されたスワップファイルはコミットしないようにしてください。
git statusコマンドで何がステージングエリアに入っているかを確認した方がいいと思います。

指摘事項の修正は内容毎にコミットの単位を分け、`FIx:`というプレフィックスをつけてコミットメッセージを作成してください。

2020-10-09 02:29 UTC, yuji91 commented on spec/factories/tasks.rb
> +		status { "todo" }
enumの値はStringではなくSymbolで定義しましょう。
```suggestion
		status { :todo }
```

2020-10-09 02:29 UTC, yuji91 commented on spec/models/task_spec.rb
> +	end
Tabでインデントされてしまっているので、`半角スペース2`でインデントするようにしてください。
また、各テストケースの間には1行空行を開けた方が見やすいですね。
```suggestion
	it "タイトルとステータスがあれば有効なこと" do
	  user = create(:user)
	  task = build(:task, user_id: user.id)
	  expect(task).to be_valid
	end

```

2020-10-09 02:29 UTC, yuji91 commented on spec/models/task_spec.rb
> +		task = build(:task, user_id: user.id, status: "")
idではなくオブジェクトを指定する形でも作成できるかと思います。
```suggestion
		task = build(:task, user: user, status: "")
```

2020-10-09 02:29 UTC, yuji91 commented on spec/models/task_spec.rb
> +		task1.valid?
task1という変数名だと、どのようなデータが入っている変数なのかが分からないので、できるだけ意味合いが伝わるような適切な命名をするように心がけましょう。
```suggestion
		another_task = build(:task, user_id: user.id)
		another_task.valid?
```

2020-10-09 02:29 UTC, yuji91 commented on spec/rails_helper.rb
> +	config.include FactoryBot::Syntax::Methods
こちらもインデントを修正頂きたいです。
```suggestion
  config.include FactoryBot::Syntax::Methods
```

2020-10-10 03:16 UTC, kenchasonakai commented on spec/models/task_spec.rb
> +	end
a31300a で修正しました

2020-10-10 03:18 UTC, kenchasonakai commented on spec/models/task_spec.rb
> +	end
36e7e67 でテストコードの下に１行開けました

2020-10-10 03:19 UTC, kenchasonakai commented on spec/factories/tasks.rb
> +		status { "todo" }
25effde でenumの値をstringからSymbolに修正しました

2020-10-10 03:21 UTC, kenchasonakai commented on spec/models/task_spec.rb
> +		task = build(:task, user_id: user.id, status: "")
ef3bd33 でidの指定からオブジェクトの指定に修正しました

2020-10-10 03:22 UTC, kenchasonakai commented on spec/models/task_spec.rb
> +		task1.valid?
864bac1 でtask1からanother_taskに変数名を修正しました

2020-10-10 03:24 UTC, kenchasonakai commented on spec/rails_helper.rb
> +	config.include FactoryBot::Syntax::Methods
a31300a でタブをスペースに修正しました

2020-10-10 04:42 UTC, yuji91 approved these changes
LGTMです！
解答例のPRも参考に確認してみてください！

2020-10-10 11:05 UTC, merged