03 system spec
kenchasonakai/sample_app_for_rspec pull request #4
Opened 2020-10-24 08:43 UTC by kenchasonakai

### 概要

### コメント
### 参考資料
### 確認方法
### 確認したこと
### 修正内容

2020-10-30 03:33 UTC, yuji91 commented on spec/spec_helper.rb
> +  #   Kernel.srand config.seed
二重でコメントアウトする必要はないかと思います！

2020-10-30 03:33 UTC, yuji91 commented on .rubocop.yml
> +#    - 'spec/**/*'
この点コメントアウトしている理由があれば説明頂けると！

2020-10-30 03:37 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +  let(:another_user) { create(:user, email: 'another_user@example.com', password: 'password', password_confirmation: 'password') }
パスワードの部分は、定義し直す必要は無さそうですね。
```suggestion
  let(:another_user) { create(:user, email: 'another_user@example.com') }
```

2020-10-30 03:39 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +        fill_in 'Deadline', with: DateTime.new(2020, 10, 31, 10, 0o0)
`0o0`の値を使わずに日付指定したいですね！

2020-10-30 03:39 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +        select 'doing', from: 'Status'
Symbol形式で選択できないか試してみて欲しいです（ダメだったらすみません）
```suggestion
        select :doing, from: 'Status'
```

2020-10-30 03:40 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +      expect(page).to have_current_path login_path, ignore_query: true
`ignore_query: true`の記載が必要かどうか念の為確認したいです！

2020-10-30 03:42 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +        end
ここ多分1行で書けそうなので、3行使わずに処理を書いた方が全体のコード量が減りますね！

2020-10-30 03:43 UTC, yuji91 commented on spec/system/users_spec.rb
> +
好みもありますが、1行開けなくてもいいかなと思います！
```suggestion
        let(:user) { create(:user) }
        before { login(user) }

```

2020-10-30 03:47 UTC, yuji91 requested changes
ざっと見て気になった点を指摘しました！

2020-10-30 08:09 UTC, kenchasonakai commented on spec/spec_helper.rb
> +  #   Kernel.srand config.seed
d5d1b98

で二重のコメントアウトを修正しました

2020-10-30 08:15 UTC, kenchasonakai commented on .rubocop.yml
> +#    - 'spec/**/*'
6b7ea02 にてコメントアウトしていた'spec/**/*'を行ごと削除しました。
rubocopでspecファイルが読み込まれず試していた時にとりあえずコメントアウトしていたものの削除忘れでした。

2020-10-30 08:21 UTC, kenchasonakai commented on spec/system/tasks_spec.rb
> +  let(:another_user) { create(:user, email: 'another_user@example.com', password: 'password', password_confirmation: 'password') }
2ea7d29 にてFactorybotで定義したものと同じ内容で再定義してしまっていたpassword, password_confirmationを削除しました。

2020-10-30 08:42 UTC, kenchasonakai commented on spec/system/tasks_spec.rb
> +        fill_in 'Deadline', with: DateTime.new(2020, 10, 31, 10, 0o0)
916215f にて0o0から00へ数値の指定を修正しました

2020-10-30 08:46 UTC, kenchasonakai commented on spec/system/tasks_spec.rb
> +        select 'doing', from: 'Status'
b8cbcf0 にてselect_fomの指定方法をシンボルに変更しました

2020-10-30 08:54 UTC, kenchasonakai commented on spec/system/tasks_spec.rb
> +      expect(page).to have_current_path login_path, ignore_query: true
b4264b9 にてignore_query: trueを削除しました。
クエリパラメータがついてしまうものはないはずなので当初はつけていませんでしたが、rubocopのオートコレクトによって生成されたのでついている方が確実ではあるからつけといた方がいいのかなという認識でした。今回のテスト結果には影響しないため削除しました。

2020-10-30 09:05 UTC, kenchasonakai commented on spec/system/users_spec.rb
> +
e87943b にてletとbeforeの間に1行開けていた書き方を修正しました。

2020-10-30 09:36 UTC, kenchasonakai commented on spec/system/tasks_spec.rb
> +        end
ab1c29d でネストしていた書き方を修正しました
c057889 でtaskとuserが最初に必ず作成されるように修正しました。
2e2005a で修正の際ズレてしまったインデントを修正しました

2020-10-31 08:01 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +        expect(page).to have_current_path task_path(2)
最初にタスクを作っていることが原因だと思うのですが、`task_path(2)`で2のIDのパスを確認させる特別な必要がないので、current_pathの確認はいっそ削除してもいいかもしれません。

2020-10-31 08:02 UTC, yuji91 commented on spec/system/user_sessions_spec.rb
> +        expect(page).to have_current_path root_path, ignore_query: true
この辺りの`ignore_query`の対応もお願いします！

2020-10-31 08:02 UTC, yuji91 commented on spec/system/user_sessions_spec.rb
> +
この部分の改行も対応をお願いします。

2020-10-31 08:03 UTC, yuji91 requested changes
指摘事項への修正を確認しました。
コミットの単位とメッセージが分けられていて良いと思います。

追加で指摘事項をコメントしたので、対応をお願いします。

提出前に以下のURLでファイル差分全体をチェックするようにしても良いかもしれないですね。
https://github.com/kenchasonakai/sample_app_for_rspec/pull/4/files

2020-11-01 06:05 UTC, kenchasonakai commented on spec/system/tasks_spec.rb
> +        expect(page).to have_current_path task_path(2)
71e1b07 でcurrent_pathの確認を削除しました

2020-11-01 06:12 UTC, kenchasonakai commented on spec/system/user_sessions_spec.rb
> +        expect(page).to have_current_path root_path, ignore_query: true
e94369e でignore_queryを削除しました

2020-11-01 06:16 UTC, kenchasonakai commented on spec/system/user_sessions_spec.rb
> +
ffef7d0 で改行を削除しました

2020-11-04 08:13 UTC, merged